/**
 * Minified by jsDelivr using Terser v5.14.1.
 * Original file: /npm/@violentmonkey/dom@2.1.3/dist/index.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
/*! @violentmonkey/dom v2.1.3 | ISC License */
!function(e,t){"object"==typeof exports&&"undefined"!=typeof module?t(exports):"function"==typeof define&&define.amd?define(["exports"],t):t((e="undefined"!=typeof globalThis?globalThis:e||self).VM=e.VM||{})}(this,(function(e){"use strict";
/*! @gera2ld/jsx-dom v2.2.1 | ISC License */const t="http://www.w3.org/1999/xlink",n={show:t,actuate:t,href:t};function o(e,t){for(var n=arguments.length,o=new Array(n>2?n-2:0),i=2;i<n;i++)o[i-2]=arguments[i];return r(e,t=Object.assign({},t,{children:1===o.length?o[0]:o}))}function r(e,t){let n;if("string"==typeof e)n=1;else{if("function"!=typeof e)throw new Error("Invalid VNode type");n=2}return{vtype:n,type:e,props:t}}function i(e){return e.children}const s={isSvg:!1};function c(e,t){Array.isArray(t)||(t=[t]),(t=t.filter(Boolean)).length&&e.append(...t)}const u={className:"class",labelFor:"for"};function l(e,t,o,r){if(t=u[t]||t,!0===o)e.setAttribute(t,"");else if(!1===o)e.removeAttribute(t);else{const i=r?n[t]:void 0;void 0!==i?e.setAttributeNS(i,t,o):e.setAttribute(t,o)}}function f(e,t){return Array.isArray(e)?e.map((e=>f(e,t))).reduce(((e,t)=>e.concat(t)),[]):a(e,t)}function a(e,t){if(void 0===t&&(t=s),null==e||"boolean"==typeof e)return null;if(e instanceof Node)return e;if(2===(null==(n=e)?void 0:n.vtype)){const{type:n,props:o}=e;if(n===i){const e=document.createDocumentFragment();if(o.children){c(e,f(o.children,t))}return e}return a(n(o),t)}var n;if((e=>"string"==typeof e||"number"==typeof e)(e))return document.createTextNode(""+e);if((e=>1===(null==e?void 0:e.vtype))(e)){let n;const{type:o,props:r}=e;if(t.isSvg||"svg"!==o||(t=Object.assign({},t,{isSvg:!0})),n=t.isSvg?document.createElementNS("http://www.w3.org/2000/svg",o):document.createElement(o),function(e,t,n){for(const o in t)"key"!==o&&"children"!==o&&"ref"!==o&&("dangerouslySetInnerHTML"===o?e.innerHTML=t[o].__html:"innerHTML"===o||"textContent"===o||"innerText"===o?e[o]=t[o]:o.startsWith("on")?e[o.toLowerCase()]=t[o]:l(e,o,t[o],n.isSvg))}(n,r,t),r.children){let e=t;t.isSvg&&"foreignObject"===o&&(e=Object.assign({},e,{isSvg:!1}));const i=f(r.children,e);null!=i&&c(n,i)}const{ref:i}=r;return"function"==typeof i&&i(n),n}throw new Error("mount: Invalid Vnode!")}function d(e){return a(e)}var p;const g=Object.assign("undefined"!=typeof VM&&(null==(p=VM)?void 0:p.versions)||{},{dom:"2.1.3"});e.Fragment=i,e.createElement=o,e.getElementsByXPath=function(e,t=document){const n=document.evaluate(e,t,null,XPathResult.ANY_TYPE,null),o=[];let r;for(;r=n.iterateNext();)o.push(r);return o},e.getTextValues=function e(t){return t.nodeType===Node.TEXT_NODE?[t.nodeValue]:t.nodeType!==Node.ELEMENT_NODE||["script","style"].includes(t.tagName.toLowerCase())?[]:Array.from(t.childNodes).flatMap(e)},e.h=o,e.hm=function(){return d(o(...arguments))},e.m=d,e.mountDom=d,e.observe=function(e,t,n){const o=new MutationObserver(((e,n)=>{t(e,n)&&r()}));o.observe(e,Object.assign({childList:!0,subtree:!0},n));const r=()=>o.disconnect();return r},e.versions=g}));
//# sourceMappingURL=/sm/edd66e4a39def3abeadece3a77824f3a5800d61587c68ba6d5cbb9d6a73b336b.map