/**
 * Minified by jsDelivr using Terser v5.19.2.
 * Original file: /npm/@violentmonkey/dom@2.1.5/dist/index.js
 *
 * Do NOT use SRI with dynamically generated files! More information: https://www.jsdelivr.com/using-sri-with-dynamic-files
 */
/*! @violentmonkey/dom v2.1.5 | ISC License */
!function(e){"use strict";
/*! @gera2ld/jsx-dom v2.2.2 | ISC License */const t=1,n=2,r="http://www.w3.org/2000/svg",o="http://www.w3.org/1999/xlink",i={show:o,actuate:o,href:o},s=e=>"string"==typeof e||"number"==typeof e,c=e=>(null==e?void 0:e.vtype)===t,u=e=>(null==e?void 0:e.vtype)===n;function l(e,r,...o){return function(e,r){let o;if("string"==typeof e)o=t;else{if("function"!=typeof e)throw new Error("Invalid VNode type");o=n}return{vtype:o,type:e,props:r}}(e,r=Object.assign({},r,{children:1===o.length?o[0]:o}))}function a(e){return e.children}const f={isSvg:!1};function d(e,t){Array.isArray(t)||(t=[t]),(t=t.filter(Boolean)).length&&e.append(...t)}const p={className:"class",labelFor:"for"};function g(e,t,n,r){if(t=p[t]||t,!0===n)e.setAttribute(t,"");else if(!1===n)e.removeAttribute(t);else{const o=r?i[t]:void 0;void 0!==o?e.setAttributeNS(o,t,n):e.setAttribute(t,n)}}function v(e,t){return Array.isArray(e)?e.map((e=>v(e,t))).reduce(((e,t)=>e.concat(t)),[]):m(e,t)}function m(e,t=f){if(null==e||"boolean"==typeof e)return null;if(e instanceof Node)return e;if(u(e)){const{type:n,props:r}=e;if(n===a){const e=document.createDocumentFragment();if(r.children){d(e,v(r.children,t))}return e}return m(n(r),t)}if(s(e))return document.createTextNode(`${e}`);if(c(e)){let n;const{type:o,props:i}=e;if(t.isSvg||"svg"!==o||(t=Object.assign({},t,{isSvg:!0})),n=t.isSvg?document.createElementNS(r,o):document.createElement(o),function(e,t,n){for(const r in t)if("key"!==r&&"children"!==r&&"ref"!==r)if("dangerouslySetInnerHTML"===r)e.innerHTML=t[r].__html;else if("innerHTML"===r||"textContent"===r||"innerText"===r||"value"===r&&["textarea","select"].includes(e.tagName)){const n=t[r];null!=n&&(e[r]=n)}else r.startsWith("on")?e[r.toLowerCase()]=t[r]:g(e,r,t[r],n.isSvg)}(n,i,t),i.children){let e=t;t.isSvg&&"foreignObject"===o&&(e=Object.assign({},e,{isSvg:!1}));const r=v(i.children,e);null!=r&&d(n,r)}const{ref:s}=i;return"function"==typeof s&&s(n),n}throw new Error("mount: Invalid Vnode!")}function h(e){return m(e)}var y;const b=Object.assign("undefined"!=typeof VM&&(null==(y=VM)?void 0:y.versions)||{},{dom:"2.1.5"});e.Fragment=a,e.createElement=l,e.getElementsByXPath=function(e,t=document){const n=document.evaluate(e,t,null,XPathResult.ANY_TYPE,null),r=[];let o;for(;o=n.iterateNext();)r.push(o);return r},e.getTextValues=function e(t){return t.nodeType===Node.TEXT_NODE?[t.nodeValue]:t.nodeType!==Node.ELEMENT_NODE||["script","style"].includes(t.tagName.toLowerCase())?[]:Array.from(t.childNodes).flatMap(e)},e.h=l,e.hm=function(...e){return h(l(...e))},e.m=h,e.mountDom=h,e.observe=function(e,t,n){const r=new MutationObserver(((e,n)=>{t(e,n)&&o()}));r.observe(e,Object.assign({childList:!0,subtree:!0},n));const o=()=>r.disconnect();return o},e.versions=b}(this.VM=this.VM||{});
//# sourceMappingURL=/sm/5744fc8402f8dcb531d7a8a7acd723efcbe1cc53627d874f7c330b0d5036d115.map
